// Design tokens sourced from DESIGN.md ("Protocol Investigative Interface")
// — read as reference and reproduced as the actual system, not copy/pasted
// markup. See docs/ux.md for how these are used across every screen.
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0b1326",
        surface: "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        outline: "#849495",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        primary: "#dbfcff",
        "on-primary": "#00363a",
        "primary-container": "#00f0ff",
        "on-primary-container": "#006970",
        "inverse-primary": "#006970",
        "primary-fixed": "#7df4ff",
        "primary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        secondary: "#c0c1ff",
        "on-secondary": "#1000a9",
        "secondary-container": "#3131c0",
        "on-secondary-container": "#b0b2ff",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",
        tertiary: "#fff5de",
        "on-tertiary": "#3b2f00",
        "tertiary-container": "#fed639",
        "on-tertiary-container": "#715d00",
        "tertiary-fixed": "#ffe179",
        "tertiary-fixed-dim": "#eac324",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#554500",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#0b1326",
        "on-background": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        lg: "0.375rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "16px",
        "stack-md": "16px",
        unit: "4px",
        "stack-sm": "8px",
        gutter: "12px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "data-label": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
